# Generated by Django 4.2.8 on 2023-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(db_column='usrDoB', default='1999-10-01'),
        ),
    ]
