# Generated by Django 4.2.8 on 2023-12-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, db_column='usrCreatedDate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(db_column='usrActive', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastEditDate',
            field=models.DateTimeField(auto_now=True, db_column='usrUpdatedDate'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='tblUsers',
        ),
    ]
