# Generated by Django 4.2.8 on 2023-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_createddate_alter_user_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastEditDate',
            field=models.DateTimeField(auto_now=True, db_column='usrUpdateDate'),
        ),
    ]
